name: Setup Docker Engine
description: Reusable Docker setup
runs:
  using: "composite"
  steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start Docker service
        run: sudo service docker start