name: Kango - CI

on: 
  push:
    branches: 
      - main
      - develop
    paths-ignore:
      - README.md
      - .gitattributes
      - .gitignore
      - compose.yaml

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java

      - name: Run tests
        run: mvn test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java

      - name: Run build
        run: mvn install
