name: Kango - CI
on: 
  push:
    branches: 
      - main
      - develop
    paths-ignore:
      - README.md
      - .gitattributes
      - .gitignore
      - compose.yaml
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - &setup-java
        name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests
        run: mvn test
    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - *setup-java
        
      - name: Run build
        run: mvn package